# Tomcat
server:
    tomcat:
        max-threads: 1000
        min-spare-threads: 30
    port: 8787

# 日志
logging:
    config: classpath:logback.xml


# 环境 dev|pro
spring:
    profiles:
        active: dev
    datasource:
        driverClassName: com.mysql.jdbc.Driver
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    thymeleaf:
        cache: false
    application:
      name: user

mybatis-plus:
    mapper-locations: classpath:/mapper/*Mapper.xml
    global-config:
        # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
        id-type: 0
        # 驼峰下划线转换
        db-column-underline: true
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: false

swagger:
    project:
        version: 0.0.1-SNAPSHOT
        title: lss-project
        description:

lss:
    name: lss
    age: 18
